baseURL = 'https://example.org/'
languageCode = 'pl-PL'
defaultContentLanguage = "pl"
title = 'Patriotyzm postÄ™powy'
theme = "PaperMod"

[params]
  ShowSidebar = true
  ShowTags = true
  ShowCategories = true
  ShowReadingTime = true

