baseURL = 'https://example.org/'
languageCode = 'pl-PL'
defaultContentLanguage = "pl"
title = 'Patriotyzm postÄ™powy'
theme = "PaperMod"

[params]
    disableTitleCapitalization = true
    disableArchiveTitleStyling  = true
    customCss = ["css/custom.css"]
