baseURL = 'https://example.org/'
languageCode = 'pl-PL'
defaultContentLanguage = "pl"
title = 'Patriotyzm postępowy'
theme = "anatole"

[params]
    disableTitleCapitalization = true
    disableArchiveTitleStyling  = true
    customCss = ["css/custom.css"]
    profilePicture="/images/logo.png"
    title = "Patriotyzm postępowy"
    preserveTaxonomyNames = true
    localizedDates = true

[taxonomies]
tag = "tags"
